게임:
  능력 재추첨 기회: 1
  능력 중복 추첨: false
  퇴장 시 탈락 체력(이하): 6
  배고픔 무한: false
  내구도 무한: false
  이 플러그인 능력 사용: true
  효과음 사용: true
  비 끄기: true
  
MOTD:
  대기 중: '&b[ 대기 중 ]'
  게임 중: '&c[ 게임 중 ]'

초반 무적:
  사용: true
  지속 시간: 300

사망:
  강제 퇴장: false
  차단: false
  탈락: false
  자연사 시 탈락 처리: false

재접속:
  허용: false
  재접속 허용 시간 제한: false
  허용 시간(초): 60

게임 시작 전 조작:
  무적: false
  PVP 방지: false
  블럭 보호: false
  명령어 금지: false
  예외 명령어:
  - ua

보급품:
  사용: false
  폭죽 사용: false
  생성 간격(초): 300

좌표 알림:
  메시지 사용: false
  폭죽 사용: false
  간격(초): 300

연속 킬:
  퍼스트 블러드 사용: false
  더블 킬 사용: false
  트리플 킬 사용: false
  쿼드라 킬 사용: false
  펜타 킬 사용: false
  더블 킬 시간(초): 15
  트리플 킬 시간(초): 15
  쿼드라 킬 시간(초): 15
  펜타 킬 시간(초): 15

어시스트:
  사용: false
  시간(초): 10

보상:
  킬: 100
  어시스트: 50
  우승 보상 공식: java.lang.Math.floor(player_count / 5) * 500 + (player_count % 5) * 30
  퍼스트 블러드: 100
  더블 킬: 100
  트리플 킬: 150
  쿼드라 킬: 200
  펜타 킬: 300

관전:
  명령어 금지: false
  예외 명령어:
  - ua
  
번지코드:
  사용: false
  로비: lobby