# 게임 시작 시 지급되는 등급 아이템 설정 파일입니다.
# 아이템 등록은 <아이템코드>:<데이터> <갯수> 로 가능하며, 데이터는 생략 가능합니다.
# 킷 등록은 <kit:킷이름> 으로 가능합니다.
사용: false
등급:
  group1:
    - 298 1
    - 299 1
    - 300 1
    - 301 1
  group2:
    - 272 1