# 게임 시작 시 지급되는 등급 아이템 설정 파일입니다.
# 아이템 등록은 <아이템코드>:<데이터> <갯수> 로 가능하며, 데이터는 생략 가능합니다.
# 킷 등록은 <kit:킷이름> 으로 가능합니다.
# 0 입력 시 아이템이 지급되지 않습니다.
사용: true
레벨: 0
갑옷:
  투구: "302"
  갑옷: "303"
  레깅스: "304"
  부츠: "305"
아이템:
- 272 1